# Generated by Django 2.2.5 on 2019-11-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20191105_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this page was  updated. Automatically generated  when the model updates.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, help_text='Unique URL path to access this page. Generated by the system.', max_length=600),
        ),
    ]
